# Generated by Django 5.0.7 on 2026-01-22 00:00

import datetime

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="wake_up_time",
            field=models.TimeField(default=datetime.time(8, 0)),
        ),
        migrations.AddField(
            model_name="user",
            name="bed_time",
            field=models.TimeField(default=datetime.time(23, 0)),
        ),
    ]

