# Generated by Django 5.0.7 on 2026-01-30 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0004_user_avatar_alter_user_photo_url"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="tg_id",
            field=models.BigIntegerField(blank=True, db_index=True, null=True, unique=True),
        ),
    ]

