# Generated by Django 5.0.7 on 2025-12-13 15:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('common', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sprint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=63)),
                ('started_at', models.DateTimeField()),
                ('ended_at', models.DateTimeField()),
                ('active', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'sprint',
            },
        ),
        migrations.CreateModel(
            name='Status',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=31)),
                ('type', models.CharField(choices=[('new', 'new'), ('in work', 'in work'), ('wait for detail', 'wait for detail'), ('info received', 'info received'), ('paused', 'paused'), ('completed', 'completed'), ('cancelled', 'cancelled'), ('deferred', 'deferred')], default='new', max_length=31)),
                ('color', models.CharField(max_length=9)),
            ],
            options={
                'db_table': 'status',
            },
        ),
        migrations.CreateModel(
            name='Subtask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=127)),
                ('completed', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'subtask',
            },
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=63)),
            ],
            options={
                'db_table': 'tag',
            },
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('started_at', models.DateTimeField(default=None, null=True)),
                ('finished_at', models.DateTimeField(default=None, null=True)),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='common.category')),
                ('sprint', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='task.sprint')),
                ('status', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='task.status')),
                ('subtasks', models.ManyToManyField(to='task.subtask')),
                ('tags', models.ManyToManyField(to='task.tag')),
            ],
            options={
                'db_table': 'task',
                'ordering': ['-created_at'],
            },
        ),
    ]
