# Generated by Django 5.0.7 on 2026-01-23 11:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0007_tag_user'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='subtask',
            options={'ordering': ['id']},
        ),
    ]
