# Generated by Django 5.0.7 on 2026-02-03 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0008_alter_subtask_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='repeat_days',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
