# Generated by Django 5.0.7 on 2026-02-03 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0009_task_repeat_days'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='repeat_until',
            field=models.DateField(blank=True, default=None, null=True),
        ),
    ]
